server.port=8081
spring.cloud.config.allow-override=true

# Força o microsserviço a se registrar e buscar os outros no Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8888/eureka
eureka.instance.prefer-ip-address=true