server.port=8082

# Garante que o serviço de notificação também informe sua localização ao Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8888/eureka
eureka.instance.prefer-ip-address=true